apiVersion: apps/{{ .Values.apiVersion }}
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: {{ template "helloworld.name" . }}
    chart: {{ template "helloworld.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
spec: 
  selector:
    matchLabels:
      app: helloworld
  template: 
    metadata:
     labels:
        app: helloworld
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: helloworld
        image: {{ .Values.helloworld.image }} 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: app-registry-secret
---
apiVersion: v1
kind: Service
metadata:
    name: helloworld-svc
spec:
    ports:
        - port: 80
          protocol: TCP
          targetPort: 80
    selector:
        app: helloworld
    type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 annotations:
  kubernetes.io/ingress.class: nginx
  kubernetes.io/ingress.allow-http: "true" 
 name: helloworld-ingress
 namespace: {{ .Release.Namespace }}
spec:
 rules:
  - host: {{ .Values.helloworld.host }}
    http:
     paths:
     - path: /
       backend:
         serviceName: helloworld-svc 
         servicePort: 80